import { useEffect, useState } from 'react'; import { ShoppingCart } from 'lucide-react'; import { parsePdf } from '../pdf-parser.js';
import type { Account, Invoice, JournalGroup, MappingRule, Page } from './types'; import { DEFAULT_ACCOUNTS, DEFAULT_MAPPING_RULES } from './data/defaults'; import { exportJournal, generateJournal } from './services/journal'; import { loadList, saveSettings } from './services/storage';
import { Login } from './components/Login'; import { ModulePicker } from './components/ModulePicker'; import { Sidebar } from './components/Sidebar'; import { ImportPage } from './pages/ImportPage'; import { ReviewPage } from './pages/ReviewPage'; import { MappingPage } from './pages/MappingPage'; import { SettingsPage } from './pages/SettingsPage';
export default function App(){ const [user,setUser]=useState<string|null>(null);const [module,setModule]=useState<'ventes'|'achats'|null>(null);const [page,setPage]=useState<Page>('import');const [invoices,setInvoices]=useState<Invoice[]>([]);const [groups,setGroups]=useState<JournalGroup[]>([]);const [fileName,setFileName]=useState('');const [rules,setRules]=useState<MappingRule[]>(()=>loadList('mappingRules',DEFAULT_MAPPING_RULES));const [accounts,setAccounts]=useState<Account[]>(()=>loadList('chartOfAccounts',DEFAULT_ACCOUNTS));const [admin,setAdmin]=useState(false);
  const [disabled,setDisabled]=useState<string|null>(null);
  useEffect(()=>saveSettings(rules,accounts),[rules,accounts]);
  useEffect(()=>{const check=async()=>{const status=await window.journalPro?.getControlStatus();setDisabled(status?.status==='disabled'?(status.message||'Application désactivée'):null)};void check();const timer=window.setInterval(()=>void check(),15*60*1000);return()=>window.clearInterval(timer)},[]);
  const navigate=(p:Page)=>{if((p==='mapping'||p==='settings')&&user!=='samer'&&!admin){const password=window.prompt('Mot de passe administrateur requis');if(password!=='07samer10')return;setAdmin(true)}setPage(p)};
  const importPdf=async(file:File,progress:(n:number,m:string)=>void)=>{if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))throw new Error('Veuillez choisir un fichier PDF');setFileName(file.name);const parsed=await parsePdf(await file.arrayBuffer(),progress);setInvoices(parsed);setGroups(generateJournal(parsed,rules))};
  const persist=()=>saveSettings(rules,accounts); const reset=()=>{setInvoices([]);setGroups([]);setFileName('')};
  if(disabled)return <div className="control-disabled"><div><h1>Application désactivée</h1><p>{disabled}</p><small>Contactez votre administrateur pour réactiver cette installation.</small></div></div>;
  if(!user)return <Login onLogin={setUser}/>; if(!module)return <ModulePicker onChoose={setModule}/>; if(module==='achats')return <div className="placeholder"><ShoppingCart/><h1>Module achats</h1><p>L'interface de traitement des achats est prête à être développée.</p><button className="btn btn-outline" onClick={()=>setModule(null)}>Changer de module</button></div>;
  return <><Sidebar page={page} count={invoices.length} onNavigate={navigate} onModules={()=>setModule(null)} onLogout={()=>{setUser(null);setModule(null);setAdmin(false)}}/><main className="main-content">{page==='import'&&<ImportPage invoices={invoices} groups={groups} onImport={importPdf} onReview={()=>setPage('review')} onReset={reset}/>} {page==='review'&&<ReviewPage groups={groups} accounts={accounts} onGroups={setGroups} onExport={()=>{if(!groups.length)return;if(groups.some(g=>g.hasMissing)&&!window.confirm('Des comptes sont manquants. Exporter quand même ?'))return;exportJournal(groups,fileName.replace(/\.pdf$/i,'')+'_journal.xlsx')}}/>}{page==='mapping'&&<MappingPage rules={rules} onChange={setRules} onSave={()=>{persist();setGroups(generateJournal(invoices,rules))}}/>}{page==='settings'&&<SettingsPage accounts={accounts} onChange={setAccounts} onSave={persist}/>}</main></>;
}
